apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: sigstore-demo
spec:
  images:
  - glob: "**"
  authorities:
  - keyless:
        identities:
          - issuer: https://token.actions.githubusercontent.com
            subject: https://github.com/lukehinds/oidc-action/.github/workflows/docker-image.yml@refs/heads/main