apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: sigstore-demo
spec:
  images:
  - glob: "**"
  authorities:
  - keyless:
        identities:
          # - issuer: https://accounts.google.com
          #   subject: {$EMAIL}@gmail.com
          - issuer: https://token.actions.githubusercontent.com
            subject: https://github.com/{GITHUB_USER}/cosign-keyless-action/.github/workflows/build-push-sign.yml@refs/heads/main