apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Values.name }}"
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.name }}.localtest.me"
    http:
      paths:
        - backend:
            service:
              name: "{{ .Values.name }}"
              port:
                number: 8080
          path: /
          pathType: ImplementationSpecific